// ALERTS ***************************************************************************************
export const ALERT_ADD = 'ALERT_ADD'
export const ALERT_REMOVE = 'ALERT_REMOVE'

// AUTH ******************************************************************************************
export const ADMIN_LOGIN_REQUEST = 'ADMIN_LOGIN_REQUEST'
export const ADMIN_LOGIN_SUCCESS = 'ADMIN_LOGIN_SUCCESS'
export const ADMIN_LOGIN_FAIL = 'ADMIN_LOGIN_FAIL'
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT'

export const ADMIN_PASSWORD_CHANGE_REQUEST = 'ADMIN_PASSWORD_CHANGE_REQUEST'
export const ADMIN_PASSWORD_CHANGE_SUCCESS = 'ADMIN_PASSWORD_CHANGE_SUCCESS'
export const ADMIN_PASSWORD_CHANGE_FAIL = 'ADMIN_PASSWORD_CHANGE_FAIL'

// PROJECTS ***********************************************************************************
export const PROJECT_ADD_REQUEST = 'PROJECT_ADD_REQUEST'
export const PROJECT_ADD_SUCCESS = 'PROJECT_ADD_SUCCESS'
export const PROJECT_ADD_FAIL = 'PROJECT_ADD_FAIL'

export const PROJECT_GET_ALL_REQUEST = 'PROJECT_GET_ALL_REQUEST'
export const PROJECT_GET_ALL_SUCCESS = 'PROJECT_GET_ALL_SUCCESS'
export const PROJECT_GET_ALL_FAIL = 'PROJECT_GET_ALL_FAIL'
export const PROJECT_ADD_NEW = 'PROJECT_ADD_NEW'
export const PROJECT_REMOVE_DELETED = 'PROJECT_REMOVE_DELETED'

export const PROJECT_REMOVE_REQUEST = 'PROJECT_REMOVE_REQUEST'
export const PROJECT_REMOVE_SUCCESS = 'PROJECT_REMOVE_SUCCESS'
export const PROJECT_REMOVE_FAIL = 'PROJECT_REMOVE_FAIL'

// EXPERIENCE *********************************************************************************
export const EXPERIENCE_ADD_REQUEST = 'EXPERIENCE_ADD_REQUEST'
export const EXPERIENCE_ADD_SUCCESS = 'EXPERIENCE_ADD_SUCCESS'
export const EXPERIENCE_ADD_FAIL = 'EXPERIENCE_ADD_FAIL'

export const EXPERIENCE_GET_ALL_REQUEST = 'EXPERIENCE_GET_ALL_REQUEST'
export const EXPERIENCE_GET_ALL_SUCCESS = 'EXPERIENCE_GET_ALL_SUCCESS'
export const EXPERIENCE_GET_ALL_FAIL = 'EXPERIENCE_GET_ALL_FAIL'
export const EXPERIENCE_ADD_NEW = 'EXPERIENCE_ADD_NEW'
export const EXPERIENCE_REMOVE_DELETED = 'EXPERIENCE_REMOVE_DELETED'

export const EXPERIENCE_REMOVE_REQUEST = 'EXPERIENCE_REMOVE_REQUEST'
export const EXPERIENCE_REMOVE_SUCCESS = 'EXPERIENCE_REMOVE_SUCCESS'
export const EXPERIENCE_REMOVE_FAIL = 'EXPERIENCE_REMOVE_FAIL'

// SKILLS *********************************************************************************
export const SKILL_ADD_REQUEST = 'SKILL_ADD_REQUEST'
export const SKILL_ADD_SUCCESS = 'SKILL_ADD_SUCCESS'
export const SKILL_ADD_FAIL = 'SKILL_ADD_FAIL'

export const SKILL_GET_ALL_REQUEST = 'SKILL_GET_ALL_REQUEST'
export const SKILL_GET_ALL_SUCCESS = 'SKILL_GET_ALL_SUCCESS'
export const SKILL_GET_ALL_FAIL = 'SKILL_GET_ALL_FAIL'
export const SKILL_ADD_NEW = 'SKILL_ADD_NEW'
export const SKILL_REMOVE_DELETED = 'SKILL_REMOVE_DELETED'

export const SKILL_REMOVE_REQUEST = 'SKILL_REMOVE_REQUEST'
export const SKILL_REMOVE_SUCCESS = 'SKILL_REMOVE_SUCCESS'
export const SKILL_REMOVE_FAIL = 'SKILL_REMOVE_FAIL'

// MESSAGES ********************************************************************************
export const MESSAGE_GET_ALL_REQUEST = 'MESSAGE_GET_ALL_REQUEST'
export const MESSAGE_GET_ALL_SUCCESS = 'MESSAGE_GET_ALL_SUCCESS'
export const MESSAGE_GET_ALL_FAIL = 'MESSAGE_GET_ALL_FAIL'
export const MESSAGE_REMOVE_DELETED = 'MESSAGE_REMOVE_DELETED'
export const MESSAGE_REMOVE_ALL_DELETED = 'MESSAGE_REMOVE_ALL_DELETED'

export const MESSAGE_REMOVE_REQUEST = 'MESSAGE_REMOVE_REQUEST'
export const MESSAGE_REMOVE_SUCCESS = 'MESSAGE_REMOVE_SUCCESS'
export const MESSAGE_REMOVE_FAIL = 'MESSAGE_REMOVE_FAIL'

export const MESSAGE_REMOVE_ALL_REQUEST = 'MESSAGE_REMOVE_ALL_REQUEST'
export const MESSAGE_REMOVE_ALL_SUCCESS = 'MESSAGE_REMOVE_ALL_SUCCESS'
export const MESSAGE_REMOVE_ALL_FAIL = 'MESSAGE_REMOVE_ALL_FAIL'

// RESUME *************************************************************************************
export const RESUME_ADD_NEW_REQUEST = 'RESUME_ADD_NEW_REQUEST'
export const RESUME_ADD_NEW_SUCCESS = 'RESUME_ADD_NEW_SUCCESS'
export const RESUME_ADD_NEW_FAIL = 'RESUME_ADD_NEW_FAIL'

export const RESUME_GET_LINK_REQUEST = 'RESUME_GET_LINK_REQUEST'
export const RESUME_GET_LINK_SUCCESS = 'RESUME_GET_LINK_SUCCESS'
export const RESUME_GET_LINK_FAIL = 'RESUME_GET_LINK_FAIL'

export const RESUME_UPDATE_NEW_LINK = 'RESUME_UPDATE_NEW_LINK'
